--- #YAML:1.0
name: Catalyst::Model::NetBlogger
abstract: Catalyst Model to post and retrieve blog entries using Net::Blogger
author: Christopher H. Laco <claco@chrislaco.com>
version: 0.03
version_from: lib/Catalyst/Model/NetBlogger.pm
installdirs: site
license: perl
requires:
  Catalyst: 5.33
  NetBlogger: 1,01
build_requires:
  Test::More: 0
recommends:
  Pod::Coverage: 0.14
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
  Test:Strict: 0.05
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
