--- 
abstract: Catalyst Model to post and retrieve blog entries using Net::Blogger
author: 
  - Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.68
license: artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-NetBlogger
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.33
  Net::Blogger: 1.01
  perl: 5.8.0
tests: t/*.t t/*/*.t
version: 0.04001
